# Generated by Django 4.0.5 on 2022-06-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_instagram',
            field=models.URLField(blank=True),
        ),
    ]
